channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.2.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - tensorflow-intel==2.15.0
  - tensorflow==2.15.0
name: mlflow-env
